import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import { Logo } from "../components/Logo";
import { YouTube, Twitch } from "../components/Icons";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Carlos Azaustre - Desarrollo JavaScript y Formación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero}>
        <header role="header" className={styles.header}>
          <h1 className={styles.logo}>
            <Logo />
          </h1>
          <nav>
            <ul className={styles.menu}>
              <li>
                <Link href="/blog">
                  <a>Blog</a>
                </Link>
              </li>
              <li>
                <Link href="/sobre-mi">
                  <a>Sobre Mi</a>
                </Link>
              </li>
              <li>
                <Link href="/mentoria">
                  <a>Mentoría</a>
                </Link>
              </li>
              <li>
                <Link href="/cursos">
                  <a>Cursos</a>
                </Link>
              </li>
            </ul>
          </nav>
          <ul className={styles.social}>
            <li>
              <Link href="//youtube.com/c/CarlosAzaustre?sub_confirmation=1">
                <a>
                  <YouTube size="30px" />
                </a>
              </Link>
            </li>
            <li>
              <Link href="//twitch.tv/carlosazaustre">
                <a>
                  <Twitch size="30px" />
                </a>
              </Link>
            </li>
          </ul>
        </header>

        <main role="main" className={styles.main}>
          <section className={styles.mainLeft}>
            <h2 className={styles.subtitle}>
              <span className={styles.subtitleGreeting}>Hola 👋🏼, soy</span>{" "}
              <span className={styles.subtitleName}>Carlos Azaustre</span>
            </h2>
            <h3 className={styles.text}>
              Llevo 10+ años trabajando en desarrollo web con JavaScript. He
              trabajado en Google, IBM y Eventbrite. Soy Google Developer Expert
              (GDE) en la categoría de Tecnologías Web y divulgador de contenido
              a través de YouTube, dónde ya somos más de 50,000 suscritos!!
            </h3>
            <Link href="https://youtube.com/c/CarlosAzaustre?sub_confirmation=1">
              <a className={styles.btnCTA}>¡Quiero aprender JavaScript!</a>
            </Link>
            <div className={styles.logos}>
              <div className={styles.logosRow}>
                <Image
                  layout="fixed"
                  width={175}
                  height={31}
                  src="/assets/eb-logo.png"
                />
                <Image
                  layout="fixed"
                  width={115}
                  height={38}
                  src="/assets/google-logo.png"
                />
              </div>
              <div className={styles.logosRow}>
                <Image
                  layout="fixed"
                  width={113}
                  height={45}
                  src="/assets/ibm-logo.png"
                />
                <Image
                  layout="fixed"
                  width={137}
                  height={57}
                  src="/assets/chefly-logo.png"
                />
              </div>
            </div>
          </section>
          <section className={styles.mainRight}>
            <Link href="https://www.amazon.com/-/es/Carlos-Azaustre/dp/B08TZ3HSYZ/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1619807979&sr=8-1">
              <a className={styles.book}>
                <Image
                  width={500}
                  height={720}
                  layout="fixed"
                  src="/assets/aprendiendo-javascript-libro.png"
                />
              </a>
            </Link>
          </section>
        </main>
      </div>
    </div>
  );
}
